In [2]:
import numpy as np
import pandas as pd #Manipulación de bases de datos
#Paqueteria para aprendizaje y analisis de datos
from scipy.spatial import distance 
#Para hacer gráficas
import matplotlib.pyplot as plt
#Representación de graficas de métodos de estadística
#import seaborn as sn

In [3]:
library, cases = pd.read_csv('/Users/cvillegas/workspace/Py-es/Expert-Syems/wk7/library.csv'), pd.read_csv('/Users/cvillegas/workspace/Py-es/Expert-Syems/wk7/cases.csv')

In [4]:
library

Outlook  Temperature  Humidity   Windy  Play
0      Sunny          Hot      High   False    No
1      Sunny          Hot      High    True    No
2   Overcast          Hot      High   False   Yes
3      Rainy         Mild      High   False   Yes
4      Rainy         Cool    Normal   False   Yes
5      Rainy         Cool    Normal    True    No
6   Overcast         Cool    Normal    True   Yes
7      Sunny         Mild      High   False    No
8      Sunny         Cool    Normal   False   Yes
9      Rainy         Mild    Normal   False   Yes
10     Sunny         Mild    Normal    True   Yes
11  Overcast         Mild      High    True   Yes
12  Overcast          Hot    Normal   False   Yes
13     Rainy         Mild      High    True    No

In [5]:
cases

Outlook  Temperature  Humidity   Windy
0     Sunny         Mild    Normal   False
1     Rainy         Cool    Normal   False
2  Overcast         Cool      High   False
3     Sunny         Cool      High    True
4     Rainy          Hot      High    True
5     Rainy         Cool      High    True

In [6]:
library.dtypes

Outlook         object
 Temperature    object
 Humidity       object
 Windy          object
 Play           object
dtype: object

In [7]:
cases.dtypes

Outlook         object
 Temperature    object
 Humidity       object
 Windy          object
dtype: object

In [8]:
library.columns

Index(['Outlook', ' Temperature', ' Humidity', ' Windy', ' Play'], dtype='object')

In [9]:
type(library)

pandas.core.frame.DataFrame

In [10]:
#Drop cuando el elemento tiene la estructura .Pandas
#Axis columna 1, axis 0 filas
base = library.drop([' Play'], axis = 1)

In [11]:
#Bases de casos, ayuda a saber con cual se parece
base

Outlook  Temperature  Humidity   Windy
0      Sunny          Hot      High   False
1      Sunny          Hot      High    True
2   Overcast          Hot      High   False
3      Rainy         Mild      High   False
4      Rainy         Cool    Normal   False
5      Rainy         Cool    Normal    True
6   Overcast         Cool    Normal    True
7      Sunny         Mild      High   False
8      Sunny         Cool    Normal   False
9      Rainy         Mild    Normal   False
10     Sunny         Mild    Normal    True
11  Overcast         Mild      High    True
12  Overcast          Hot    Normal   False
13     Rainy         Mild      High    True

In [12]:
#Se usara recuperación para muestra problema
#Get dummies representa todos los datos en combinación binaria
#0 cuando se cumpla, 
base = pd.get_dummies(base)
problems = pd.get_dummies(cases)

In [13]:
base

Outlook_Overcast  Outlook_Rainy  Outlook_Sunny   Temperature_ Cool  \
0                  0              0              1                   0   
1                  0              0              1                   0   
2                  1              0              0                   0   
3                  0              1              0                   0   
4                  0              1              0                   1   
5                  0              1              0                   1   
6                  1              0              0                   1   
7                  0              0              1                   0   
8                  0              0              1                   1   
9                  0              1              0                   0   
10                 0              0              1                   0   
11                 1              0              0                   0   
12                 1              0              0                   0   
13                 0              1              0                   0   

     Temperature_ Hot   Temperature_ Mild   Humidity_ High   Humidity_ Normal  \
0                   1                   0                1                  0   
1                   1                   0                1                  0   
2                   1                   0                1                  0   
3                   0                   1                1                  0   
4                   0                   0                0                  1   
5                   0                   0                0                  1   
6                   0                   0                0                  1   
7                   0                   1                1                  0   
8                   0                   0                0                  1   
9                   0                   1                0                  1   
10                  0                   1                0                  1   
11                  0                   1                1                  0   
12                  1                   0                0                  1   
13                  0                   1                1                  0   

     Windy_ False   Windy_ True  
0               1             0  
1               0             1  
2               1             0  
3               1             0  
4               1             0  
5               0             1  
6               0             1  
7               1             0  
8               1             0  
9               1             0  
10              0             1  
11              0             1  
12              1             0  
13              0             1

In [14]:
np.shape(base)

(14, 10)

In [15]:
problems

Outlook_Overcast  Outlook_Rainy  Outlook_Sunny   Temperature_ Cool  \
0                 0              0              1                   0   
1                 0              1              0                   1   
2                 1              0              0                   1   
3                 0              0              1                   1   
4                 0              1              0                   0   
5                 0              1              0                   1   

    Temperature_ Hot   Temperature_ Mild   Humidity_ High   Humidity_ Normal  \
0                  0                   1                0                  1   
1                  0                   0                0                  1   
2                  0                   0                1                  0   
3                  0                   0                1                  0   
4                  1                   0                1                  0   
5                  0                   0                1                  0   

    Windy_ False   Windy_ True  
0              1             0  
1              1             0  
2              1             0  
3              0             1  
4              0             1  
5              0             1

In [16]:
#Para sacar la covarianza de las características
#variación con respecto a la media de cada característica
covariance_matrix = base.cov()
#Para el calculo de distancia se necesita la inversa de la covarianza
inverse_covariance_matrix = np.linalg.pinv(covariance_matrix)

In [17]:
covariance_matrix

Outlook_Overcast  Outlook_Rainy  Outlook_Sunny  \
Outlook_Overcast            0.219780      -0.109890      -0.109890   
Outlook_Rainy              -0.109890       0.247253      -0.137363   
Outlook_Sunny              -0.109890      -0.137363       0.247253   
 Temperature_ Cool         -0.010989       0.043956      -0.032967   
 Temperature_ Hot           0.065934      -0.109890       0.043956   
 Temperature_ Mild         -0.054945       0.065934      -0.010989   
 Humidity_ High             0.000000      -0.038462       0.038462   
 Humidity_ Normal           0.000000       0.038462      -0.038462   
 Windy_ False              -0.021978       0.010989       0.010989   
 Windy_ True                0.021978      -0.010989      -0.010989   

                     Temperature_ Cool   Temperature_ Hot   Temperature_ Mild  \
Outlook_Overcast             -0.010989           0.065934           -0.054945   
Outlook_Rainy                 0.043956          -0.109890            0.065934   
Outlook_Sunny                -0.032967           0.043956           -0.010989   
 Temperature_ Cool            0.219780          -0.087912           -0.131868   
 Temperature_ Hot            -0.087912           0.219780           -0.131868   
 Temperature_ Mild           -0.131868          -0.131868            0.263736   
 Humidity_ High              -0.153846           0.076923            0.076923   
 Humidity_ Normal             0.153846          -0.076923           -0.076923   
 Windy_ False                -0.021978           0.054945           -0.032967   
 Windy_ True                  0.021978          -0.054945            0.032967   

                     Humidity_ High   Humidity_ Normal   Windy_ False  \
Outlook_Overcast       0.000000e+00       0.000000e+00      -0.021978   
Outlook_Rainy         -3.846154e-02       3.846154e-02       0.010989   
Outlook_Sunny          3.846154e-02      -3.846154e-02       0.010989   
 Temperature_ Cool    -1.538462e-01       1.538462e-01      -0.021978   
 Temperature_ Hot      7.692308e-02      -7.692308e-02       0.054945   
 Temperature_ Mild     7.692308e-02      -7.692308e-02      -0.032967   
 Humidity_ High        2.692308e-01      -2.692308e-01       0.000000   
 Humidity_ Normal     -2.692308e-01       2.692308e-01       0.000000   
 Windy_ False          0.000000e+00       0.000000e+00       0.263736   
 Windy_ True           8.540177e-18      -8.540177e-18      -0.263736   

                     Windy_ True  
Outlook_Overcast    2.197802e-02  
Outlook_Rainy      -1.098901e-02  
Outlook_Sunny      -1.098901e-02  
 Temperature_ Cool  2.197802e-02  
 Temperature_ Hot  -5.494505e-02  
 Temperature_ Mild  3.296703e-02  
 Humidity_ High     8.540177e-18  
 Humidity_ Normal  -8.540177e-18  
 Windy_ False      -2.637363e-01  
 Windy_ True        2.637363e-01

In [18]:
inverse_covariance_matrix

array([[ 2.3711591 , -1.45657535, -0.91458375,  0.48307005, -1.01553023,
         0.53246017,  0.16831634, -0.16831634,  0.30738852, -0.30738852],
       [-1.45657535,  2.42444844, -0.96787309, -0.69579417,  1.35779511,
        -0.66200093, -0.05588882,  0.05588882, -0.30283943,  0.30283943],
       [-0.91458375, -0.96787309,  1.88245684,  0.21272412, -0.34226488,
         0.12954076, -0.11242751,  0.11242751, -0.00454909,  0.00454909],
       [ 0.48307005, -0.69579417,  0.21272412,  3.71942278, -2.53362661,
        -1.18579617,  1.52914417, -1.52914417,  0.374975  , -0.374975  ],
       [-1.01553023,  1.35779511, -0.34226488, -2.53362661,  3.47637139,
        -0.94274478, -0.96440712,  0.96440712, -0.59008198,  0.59008198],
       [ 0.53246017, -0.66200093,  0.12954076, -1.18579617, -0.94274478,
         2.12854096, -0.56473705,  0.56473705,  0.21510698, -0.21510698],
       [ 0.16831634, -0.05588882, -0.11242751,  1.52914417, -0.96440712,
        -0.56473705,  1.58795741, -1.58795741

In [19]:
#Primer dato fila, segundo dato columna
case_row = problems.loc[0, :]
print(case_row)

Outlook_Overcast      0
Outlook_Rainy         0
Outlook_Sunny         1
 Temperature_ Cool    0
 Temperature_ Hot     0
 Temperature_ Mild    1
 Humidity_ High       0
 Humidity_ Normal     1
 Windy_ False         1
 Windy_ True          0
Name: 0, dtype: uint8


In [20]:
# matriz de zeros para almacenar distancias
distances = np.zeros(base.shape[0])
print(distances)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
# Calcular distncia con cada elemento de la base de datos
# toma cada elemento de la lista y lo procesa con cada uno.
for j in range(base.shape[0]):

  base_row = base.loc[j, :]

  #Calcular distancia mahalanobis
  distances[j] = distance.mahalanobis(case_row, base_row, inverse_covariance_matrix)

In [22]:
distances

array([450.33859938, 573.92013983, 496.28525781, 502.30442581,
       554.70168707, 605.37490234, 661.74946102, 320.07602248,
       491.17495752, 396.43161734, 261.22062755, 536.98048319,
       497.31277526, 584.62927925])

In [23]:
# recuperar el indice con la distancia minima
# en caso de multiples toma la primera en orden ascendente de indice
min_distance_row = np.argmin(distances)
print(min_distance_row)

10


In [24]:
#Recuperar caso sin codificar y agregar solución adquirida
# Append - te ayuda a fusionar la solución recuperada para sacar la conclusión
case = np.append(cases.iloc[0, :], library.iloc[min_distance_row, -1])
print(case)

['Sunny' ' Mild' ' Normal' ' False' ' Yes']


In [25]:
print(f'> Para el caso/problema [0]: {cases.iloc[0, :].to_numpy()}, la solución {case[-1]}')

> Para el caso/problema [0]: ['Sunny' ' Mild' ' Normal' ' False'], la solución  Yes


In [26]:
# Agregarla nueva solución a la libreria
case = pd.Series(case, index = library.columns)     #Problema con la solución

library = library.append(case, ignore_index= True)  #Actualizar libreria

/var/folders/c0/xv7wtgj56454qb2jhrb4nn9c0000gn/T/ipykernel_3375/2526365707.py:4: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  library = library.append(case, ignore_index= True)  #Actualizar libreria


In [27]:
case

Outlook           Sunny
 Temperature       Mild
 Humidity        Normal
 Windy            False
 Play               Yes
dtype: object

In [28]:
library

Outlook  Temperature  Humidity   Windy  Play
0      Sunny          Hot      High   False    No
1      Sunny          Hot      High    True    No
2   Overcast          Hot      High   False   Yes
3      Rainy         Mild      High   False   Yes
4      Rainy         Cool    Normal   False   Yes
5      Rainy         Cool    Normal    True    No
6   Overcast         Cool    Normal    True   Yes
7      Sunny         Mild      High   False    No
8      Sunny         Cool    Normal   False   Yes
9      Rainy         Mild    Normal   False   Yes
10     Sunny         Mild    Normal    True   Yes
11  Overcast         Mild      High    True   Yes
12  Overcast          Hot    Normal   False   Yes
13     Rainy         Mild      High    True    No
14     Sunny         Mild    Normal   False   Yes

## Unir todo el código

In [ ]:
base = library.iloc[:, range(library.shape[1] - 1)]
base = pd.get_dummies(base)
problems = pd.get_dummies(cases)